terraform-aws-modules/terraform-aws-rds

examples/complete/main.tf
main.tf
modules/db_instance/main.tf
modules/db_instance/variables.tf
variables.tf

I've added `encrypted` as a module variable to passthrough the value to the `aws_db_instance`.`storage_encrypted` parameter.
The documentation does not specify that more parameters are required but I'm not 100% sure to be honest.

Using `storage_encrypted` to set the db_instance.storage_encrypted

---

README.md
examples/complete/main.tf
examples/enhanced_monitoring/README.md
examples/enhanced_monitoring/main.tf
main.tf
modules/db_instance/main.tf
modules/db_instance/variables.tf
variables.tf

Re-working of https://github.com/terraform-community-modules/tf_aws_rds/pull/37
(plus a `terraform fmt` :) )

Add enhanced monitoring

---

README.md
examples/complete/main.tf
main.tf
modules/db_instance/main.tf
modules/db_instance/variables.tf
variables.tf

In its current state the module will provision an RDS instance just fine, however, because skip_final_snapshot is set to false by default AWS wont allow the RDS instance to be deleted.  The only way I found to solve this was to require the setting of final_snapshot_identifier as I wanted to be conservative and not default to skipping the final snapshot by default.

support final_snapshot_identifier

---

README.md
examples/complete/mysql/main.tf
examples/complete/oracle/README.md
examples/complete/oracle/main.tf
examples/complete/oracle/outputs.tf
main.tf
modules/db_instance/main.tf
modules/db_instance/variables.tf
variables.tf

Added iam_database_authentication_enabled and license_model model

---

main.tf
modules/db_instance/main.tf
modules/db_instance/variables.tf
variables.tf

Adds support for `snapshot_identifier` argument which provides support for using an existing snapshot to build the instance.

Adds support for snapshot_identifier

---

modules/db_subnet_group/outputs.tf

Accessing `aws_db_subnet_group.this` when its `count = 0` is an error, so we need to instead access it via splat syntax and then apply a default value for when the resulting list is empty.
This error was previously suppressed by Terraform's behavior of ignoring errors in output expressions. Such errors are no longer ignored as of Terraform 0.11.0.

db_subnet_group: fix failing output expressions

---

modules/db_parameter_group/main.tf

aws_db_parameter_group (or AWS?) does not support removing previously
defined parameters.
I thought I'd give "taint" a spin and force the parameter group to be
recreated.  terraform tried to delete the parameter group but failed as
it's still in use.
This change allows terraform to migrate the RDS instance to the new
parameter group before destroying the old.

Add create_before_destroy to parameter group

---

modules/db_instance/main.tf
modules/db_instance/variables.tf

We use db_instance module directly and need to define the availability zone per instance.

Add availability zone to instance ressource module

---

main.tf
modules/db_instance/main.tf
modules/db_instance/outputs.tf
modules/db_instance/variables.tf
modules/db_parameter_group/main.tf
modules/db_subnet_group/main.tf
variables.tf

I want to be able to conditionally create databases. For example, I may only want read replica databases in the staging and production environments. Lower tiered environments would not have a read replica. The count variable provides that flexibility while maintaining the DRY principle. In the absence of this variable, I have to maintain multiple, environment specific, terraform files.

Support conditional creation for the database too.

---

main.tf
variables.tf

If the variable not specify then use the db_parameter_group module
This mimics the work done in PR #38 about `db_subnet_group_name`

Enable db_parameter_group_name variable

---

README.md
examples/complete-mssql/README.md
examples/complete-mssql/main.tf
examples/complete-mssql/outputs.tf
examples/complete-oracle/main.tf
main.tf
modules/db_instance/main.tf
modules/db_instance/outputs.tf
modules/db_instance/variables.tf
variables.tf

MSSQL: Adding two missing arguments for aws_db_instance: timezone & character_set_name

---

README.md
main.tf
modules/db_instance/README.md
modules/db_instance/main.tf
modules/db_instance/variables.tf
variables.tf

Add ability to set terraform timeouts{} map for aws_db_instance resources

---

README.md
examples/complete-mssql/main.tf
examples/complete-mysql/main.tf
examples/complete-oracle/main.tf
examples/complete-postgres/main.tf
examples/enhanced-monitoring/main.tf
main.tf
modules/db_instance/main.tf
modules/db_instance/variables.tf
variables.tf

The latest aws provider ([1.39.0](https://github.com/terraform-providers/terraform-provider-aws/releases/tag/v1.39.0)) support new aws rds feature [database deletion protection](https://aws.amazon.com/about-aws/whats-new/2018/09/amazon-rds-now-provides-database-deletion-protection/)
This PR is adding this feature in the module.

Add deletion protection argument

---

README.md
examples/complete-mssql/README.md
examples/complete-mysql/README.md
examples/complete-oracle/README.md
examples/complete-postgres/README.md
main.tf
modules/db_instance/README.md
modules/db_option_group/README.md
modules/db_parameter_group/README.md
modules/db_parameter_group/data.tf
modules/db_parameter_group/main.tf
modules/db_parameter_group/outputs.tf
modules/db_parameter_group/variables.tf
modules/db_subnet_group/README.md
variables.tf

This change allows the user to create the parameter group with a custom name.
It adds a new parameter: `use_parameter_group_name_prefix` which allow the user to specify manually whether or not to use a prefix with the parameter group name (default: true).
If `use_parameter_group_name_prefix` is false, and `parameter_group_name` is not passed, `identifier` is used.
I found I also needed to add the capability to set the parameter group description, since it can't be changed without deleting/recreating the group. Since the purpose of these changes is to allow me to import an existing, active parameter group, it's important to be able to do that without triggering a delete.

Allow create of parameter group with custom name

---

README.md
examples/replica-mysql/README.md
examples/replica-mysql/main.tf
examples/replica-mysql/outputs.tf
examples/replica-postgres/README.md
examples/replica-postgres/main.tf
examples/replica-postgres/outputs.tf
modules/db_instance/README.md
modules/db_instance/outputs.tf

This breaks plan when trying to create a read replica without setting
the master password:
`* module.database.module.db_instance.local.this_db_instance_password: local.this_db_instance_password: Resource 'aws_db_instance.this' does not have attribute 'password' for variable 'aws_db_instance.this.*.password'`
Less invasive solution for #103 . Although I'm working with MariaDB not Postgres.
Need to set password and username to empty strings. Maybe will be better under TF 0.12 with a null value?

Remove unused submodule output

---

README.md
examples/complete-postgres/main.tf
modules/db_instance/README.md
modules/db_instance/variables.tf
variables.tf

Adds additional export values specific to PostgreSQL per https://www.terraform.io/docs/providers/aws/r/db_instance.html#enabled_cloudwatch_logs_exports

Updates cloudwatch logs exports for PostgreSQL

---

modules/db_parameter_group/variables.tf

The default value has the wrong type, leading to the module not getting initialized and causing applying phase to fail.
Fixing the default value to an empty list.

Fixed variable default for parameters

---

main.tf
modules/db_instance/main.tf
modules/db_instance/variables.tf
variables.tf

AWS provider v2.12 supports performance_insights_enabled what is missing in the current module. This allows using this feature for Terraform version 0.11.X.

Add support of performance_insights_enabled

---

main.tf

I see this error when passing "var.create_db_option_group" as `false`:
```
Error: module.db_worker_replica.local.enable_create_db_option_group: local.enable_create_db_option_group: __builtin_StringToInt: strconv.ParseInt: parsing "false": invalid syntax in:
${var.option_group_name == "" && var.engine != "postgres" ? var.create_db_option_group : 0}
```
This PR seems to fix it.
Edit: Further investigation suggests that the problem occurs when `create_db_option_group` is passed in as a string, eg:
```
locals {
some_flag = "${some_condition ? true : false}"
}
module "db" {
source  = "terraform-aws-modules/rds/aws"
version = "1.28.0"
create_db_option_group    = "${local.some_flag}"
# rest of params
}
```
A workaround is to pass in 1/0 instead of "true"/"false":
```
create_db_option_group    = …
```

Use false instead of 0 in enable_create_db_option_group flag

---

README.md
main.tf
modules/db_instance/main.tf
modules/db_instance/variables.tf
variables.tf

#141 
I've simply added the parameters and variables. It's tested for RDS PostgreSQL!

Support for max_allocated_storage

---

main.tf

This PR is a follow-up of PR #118.
This is the exact same changeset than #137 but for the `create_db_subnet_group`
variable.

Use boolean value in condition

---

main.tf
modules/db_instance/main.tf
modules/db_instance/variables.tf
variables.tf

This PR adds the option to set the ca_cert_identifier
As the current CA is expiring 5th March 2020 i need to update my clusters to use the new CA before that. The default is currently set to the old one to not break any existing installations.
This will fix #171
https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.SSL-certificate-rotation.html

add support for ca_cert_identifier option

---

variables.tf

Update default CA Certificate identifier variable to `rds-ca-2019` to avoid interruption of future RDS instances by March 5, 2020.

Update CA Certificate identifier default to 'rds-ca-2019'

---

README.md
main.tf
variables.tf

This fixes issue; https://github.com/terraform-aws-modules/terraform-aws-rds/issues/107
By explicitly stating a value for `create_db_option_group` then you can use a computed value for `option_group_name`.

Fix `enable_create_db_option_group` to use override first & computed second

---

modules/db_instance/README.md
modules/db_instance/variables.tf

- Update `db_instance` sub-module to use same default ca_cert_identifier as the root level module default

Fix / CA Cert Instance Default

---

modules/db_instance/README.md
modules/db_instance/variables.tf

Same as #189  but for terraform011 branch.
Sets default value for ca_cert_identifer for internal module.
Also, some terraform-docs re-formatting

Set ca_cert_identifier default for internal module

---

versions.tf

Updated the minimum version of the AWS provider so that `ca_cert_identifier` could be set.
The current minimum version appears to work for everything else but was not updated when adding support for `ca_cert_identifier`. This causes errors when users meet the requirements laid out in the file but not
Fixes #224 
This should not break backwards compatibility.

fix: Update minimum provider version to account for ca_cert_identifier

---

.pre-commit-config.yaml
README.md
examples/complete-mssql/README.md
examples/complete-mysql/README.md
examples/complete-oracle/README.md
examples/complete-postgres/README.md
examples/enhanced-monitoring/README.md
examples/replica-mysql/README.md
examples/replica-postgres/README.md
main.tf
modules/db_instance/README.md
modules/db_instance/main.tf
modules/db_instance/variables.tf
modules/db_option_group/README.md
modules/db_parameter_group/README.md
modules/db_subnet_group/README.md
variables.tf
versions.tf

add handling for delete_automated_backups flag
the new option was added in version 2.49 of the tf provider, so it would be nice to have it in the module

feat: add handling for delete_automated_backups flag

---

README.md
variables.tf

I changed the doc to reflect reality on the **storage_type** variable.
The documentation is somewhat confusing, the description explains it defaults to "standard", and the field "default" of the table reads "gp2".
We had to read the code to guess the real default storage_type (gp2).
None.
I read the doc after the change: it was not confusing anymore.

fix: documentation for default storage type

---

README.md
examples/complete-mssql/README.md
examples/complete-mysql/README.md
examples/complete-oracle/README.md
examples/complete-postgres/README.md
examples/enhanced-monitoring/README.md
examples/replica-mysql/README.md
examples/replica-postgres/README.md
modules/db_instance/README.md
modules/db_option_group/README.md
modules/db_parameter_group/README.md
modules/db_subnet_group/README.md

- update documentation based on latest `terraform-docs` which includes module and resource sections
- these are two new sections provided by [`terraform-docs` now](https://github.com/terraform-docs/terraform-docs/releases/tag/v0.11.0)
No
N/A

chore: update documentation based on latest `terraform-docs` which includes module and resource sections

---

.pre-commit-config.yaml

- add `terraform_validate` hook to pre-commit checks
- needed for static checks; I assumed this was in there but it wasn't so adding in to be consistent
- no
- static check github action

chore: add `terraform_validate` hook to pre-commit checks

---

README.md
examples/complete-mssql/README.md
examples/complete-mysql/README.md
examples/complete-oracle/README.md
examples/complete-postgres/README.md
examples/enhanced-monitoring/README.md
examples/replica-mysql/README.md
examples/replica-postgres/README.md

- update `README.md` documentation
- I should have included these changes in my last PR to correct the documentation
- No
- Document change only

chore: update `README.md` documentation

---

README.md
examples/option-groups/README.md
examples/option-groups/main.tf
examples/option-groups/outputs.tf
examples/option-groups/versions.tf
main.tf
modules/db_option_group/README.md
modules/db_option_group/main.tf
modules/db_option_group/variables.tf
variables.tf

- update option group `name` to use `option_group_name` provided by root module
- update option group to allow users to select to use `name_prefix` or `name` depending on value of `option_group_use_name_prefix`
- when `engine == 'postgresql'`, no option group is created and a null value provided to the root module ([PostgreSQL does not use option groups](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_WorkingWithOptionGroups.html))
- added an example project to verify/validate changes and also updated the `README.md` to show different configuration combinations for users
- give users the ability to better control the management of option groups and to avoid having to set values for PostgreSQL where option groups are not utilized
Closes #188 
Closes #230
Closes #251 
Closes …

fix: update option group to fix name vs. name_prefix and conditional creation for postgresql

---

README.md
examples/complete-mssql/main.tf
modules/db_instance/README.md
modules/db_instance/main.tf
modules/db_instance/variables.tf
variables.tf

Adds support for `character_set_name` for MSSQL RDS instances.
Without this value the default collation cannot be set on MSSQL RDS instances, which in turn affects database created without specifying a collation. Default collation may need to be changed as per client requirements
This PR addresses the outstanding changes in #216 
This does not break anything - default remains "".
Tested deploying a v15.0 Standard Edition server, with and without the value set.
Also tested in #216
Default collation was set as expected.

feat: Add support for character_set_name with MSSQL Server

---

README.md
examples/groups/main.tf
main.tf
modules/db_subnet_group/README.md
modules/db_subnet_group/main.tf
modules/db_subnet_group/variables.tf
variables.tf

- remove use of `var.identifier` from sub-module and instead rely on `var.name` 
- allow for either `name` or `name_prefix` in the subnet sub-module; currently defaults `name_prefix`
- working towards consistent use of `name` versus `name_prefix` for the sub-modules as well as in the root module. This is a continuation of #302 and #304 which should now conclude the standardization of `name` and `name_prefix` for the sub-modules
Closes #42
Closes #48
Closes #121
Closes #209
Closes #223
Closes #250
Closes #280 
Closes #290 
No - other than description change below, there should be no changes for users
For users who are looking to upgrade, they should perform the following change if they wish to avoid any changes:
```hcl
...
db_subnet_group_description = "Database subnet group for …
```

fix: update subnet group to fix name vs. name_prefix

---

README.md
examples/complete-mysql/main.tf

I thought it would be good to use the proper UTF8 encoding in the MySQL examples, just to educate people who may not be aware that MySQL's utf8 only stores 3 bytes per char so is not proper utf8. utf8mb4 is the proper UTF8 encoding to use in MySQL.
Just to help maybe one or two people who may end up using the utf8 encoding by mistake.
None
I use this in my own terraform code.

Use utf8mb4 in mysql examples

---

README.md
modules/db_instance/README.md
modules/db_instance/main.tf
modules/db_instance/variables.tf
variables.tf

- remove default values and replace with `null` to use upstream default settings
- the default values provided by the AWS provider/API will change periodically. instead of hard-coding those values in this module as the module default values, switching to `null` will allow the module to be flexible and change with the upstream source as needed
Closes #235
Closes #273 
- No
- tested using `complete-postgresql` - no diff change between `master` and this PR

chore: remove default values and replace with `null` to use upstream default settings

---

examples/replica-mysql/main.tf
examples/replica-postgres/main.tf
main.tf
modules/db_instance/main.tf

- correct db subnet group name for replica scenario and update replica examples. a subnet group name is not required when using replication for RDS so it should be set to null
- fix for #316 
- no
- tested using:
- `examples/complete-postgresql`
- `examples/replica-mysql`
- `examples/replica-postgresql`

fix: correct db subnet group name for replica scenario and update replica examples

---

examples/complete-mssql/README.md
examples/complete-mssql/main.tf
examples/complete-mssql/outputs.tf
examples/complete-mysql/README.md
examples/complete-mysql/main.tf
examples/complete-mysql/outputs.tf
examples/complete-postgres/README.md
examples/complete-postgres/main.tf
examples/complete-postgres/outputs.tf
modules/db_instance/main.tf

- correct monitoring role ARN lookup logic by moving out to a local variable and simplify logic used to be more clear
- Corrects issue with monitoring role 
Closes #311 
- No
- tested on `complete-mssql` and `complete-postgresql`

fix: correct monitoring role ARN lookup

---

.github/workflows/pre-commit.yml
README.md
examples/complete-mssql/README.md
examples/complete-mysql/README.md
examples/complete-oracle/README.md
examples/complete-postgres/README.md
examples/enhanced-monitoring/README.md
examples/groups/README.md
examples/replica-mysql/README.md
examples/replica-postgres/README.md
examples/s3-import-mysql/README.md
modules/db_instance/README.md
modules/db_option_group/README.md
modules/db_parameter_group/README.md
modules/db_subnet_group/README.md

- update documentation and pin `terraform_docs` version to avoid future changes
- pin version to avoid unnecessary updates when a PR coincides with a version update for `terraform_docs`
- no
- documentation change only - ci/cd should pass checks

chore: update documentation and pin `terraform_docs` version to avoid future changes

---

.github/workflows/pre-commit.yml
.pre-commit-config.yaml
README.md
examples/complete-mssql/outputs.tf
examples/complete-mysql/outputs.tf
examples/complete-oracle/outputs.tf
examples/complete-postgres/outputs.tf
examples/enhanced-monitoring/outputs.tf
examples/replica-mysql/outputs.tf
examples/replica-postgres/outputs.tf
examples/s3-import-mysql/outputs.tf
modules/db_instance/outputs.tf
outputs.tf

- mark sensitive outputs to support Terraform 0.15.x
- Closes #328
- No
- Tested on `examples/complete-postgres` and checked with just plans on remaining examples

fix: mark sensitive outputs to support Terraform 0.15.x

---

README.md

I spent a good 20 minutes trying to figure out the correct output names. Turns out the docs show the output names from V3 but the example to copy is pinning to 2.X
Readme isn't going to help users who are new to the module.
No
I can update some if needed, but the extent of testing was that it made my build green.

chore: Update README.md to current version

---

.pre-commit-config.yaml
README.md
examples/complete-mssql/README.md
examples/complete-mssql/main.tf
examples/complete-mysql/README.md
examples/complete-mysql/main.tf
examples/complete-oracle/README.md
examples/complete-oracle/main.tf
examples/complete-postgres/README.md
examples/complete-postgres/main.tf
main.tf
modules/db_instance/README.md
modules/db_instance/variables.tf
modules/db_option_group/README.md
modules/db_option_group/variables.tf
modules/db_parameter_group/README.md
modules/db_parameter_group/variables.tf
variables.tf

- add default values to allow for completely disabling module with bare minimum input
- this allows users to completely disable any resource creation by setting the bare minimum amount of inputs and without running into issues (i.e. - `coalesce()` on empty values)
Closes #335
Closes #341 
- No
- validated with `complete-postgresql`

fix: add default values to allow for completely disabling module with bare minimum input

---

README.md

Since create_option_group is still in the README, modify it to create_db_option_group.
I got an error referring to the README.
None.
Just use old parameter.
```hcl
create_option_group   = false
```

docs: create_option_group -> create_db_option_group in README

---

README.md
examples/complete-postgres/main.tf
main.tf
modules/db_instance/README.md
modules/db_instance/main.tf
modules/db_instance/variables.tf
variables.tf

- add new parameter `monitoring_role_description` to set description for Performance Insights IAM role
Closes #333 
This change doesn't break backward compatibility with current major version
I've tested and validated changes using the `complete-postgres` example with Terraform v1.0.3

feat: Add new parameter monitoring_role_description

---

main.tf

- Correct random password lifecycle by eagerly creating random password value. Instead of linking the random password resource generation to whether or not the instance is a replica in the root, just let the random password eagerly create a value; whether or not the password value generated is used is handled by the `db_instance` sub-module regardless https://github.com/terraform-aws-modules/terraform-aws-rds/blob/master/modules/db_instance/main.tf#L8
- Fix lifecycle dependency issue causing errors when trying to use replicas
- Closes #386 
- No

fix: Correct random password lifecycle by eagerly creating random password value

---

README.md
examples/complete-mssql/README.md
examples/complete-mssql/versions.tf
examples/complete-mysql/README.md
examples/complete-mysql/versions.tf
examples/complete-oracle/README.md
examples/complete-oracle/versions.tf
examples/complete-postgres/README.md
examples/complete-postgres/versions.tf
examples/cross-region-replica-postgres/README.md
examples/cross-region-replica-postgres/versions.tf
examples/enhanced-monitoring/README.md
examples/enhanced-monitoring/versions.tf
examples/groups/README.md
examples/groups/versions.tf
examples/replica-mysql/README.md
examples/replica-mysql/versions.tf
examples/replica-postgres/README.md
examples/replica-postgres/versions.tf
examples/s3-import-mysql/README.md
examples/s3-import-mysql/versions.tf
modules/db_instance/README.md
modules/db_instance/main.tf
modules/db_instance/versions.tf
versions.tf

This adds `source_db_instance_automated_backups_arn` parameter to the `restore_to_point_in_time` block in `aws_db_instance` resource.
Ability to use feature added in https://github.com/hashicorp/terraform-provider-aws/pull/23086
Closes #397 
None

feat: Support `source_db_instance_automated_backups_arn` parameter in `restore_to_point_in_time` block

---

examples/complete-mssql/main.tf

Domain join fails in the current `complete-mssql` example. 
The security group for the database needs an outbound rule that allows the db to communicate with the directory.
AWS docs: 
https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_SQLServerWinAuth.html
Note: There are other open PRs that contain fixes for this `complete-mssql` example to apply successfully outside of this particular issue.
- Closes #336
No

chore: Fix MSSQL example add egress security group rule for db to directory services

---

.pre-commit-config.yaml
README.md
modules/db_instance/README.md
modules/db_instance/main.tf
modules/db_instance/versions.tf
modules/db_instance_automated_backups_replication/versions.tf
modules/db_option_group/README.md
modules/db_option_group/versions.tf
modules/db_parameter_group/README.md
modules/db_parameter_group/versions.tf
modules/db_subnet_group/README.md
modules/db_subnet_group/versions.tf
variables.tf
versions.tf

- Update minimum supported Terraform version to v1.x
- Update minimum supported AWS provider version to at least v4.x 
- Mark `password` input variable as sensitive
- Remove `ignore_changes` lifecycle block from `db_instance` since this should be resolved by Terraform (v1.2+) now. Similar to https://github.com/terraform-aws-modules/terraform-aws-eks/pull/2114
- Closes #372 
- Closes #401 
- Closes #411 
- Relates to #412 
- Yes; major version bumps for Terraform and AWS provider

feat!: Update Terraform and provider versions to v1.x and v4.x, mark password input as sensitive

---

examples/s3-import-mysql/README.md
examples/s3-import-mysql/main.tf
modules/db_instance/main.tf

Adding `depends_on` so that the cloudwatch log groups are created before and destroyed after the db instance if creating cloudwatch log groups with this module. 
Fixed `example/s3-import-mysql` to include updated s3 module. 
https://github.com/terraform-aws-modules/terraform-aws-rds/issues/419
No.

fix: Cloudwatch Log Group deletion db_instance dependency

---

modules/db_instance/outputs.tf

`name` is deprecated in favor of `db_name`
Fixes warning in terraform plan output:
```
│ Warning: Deprecated attribute
│ 
│   on .terraform/modules/db_instance/outputs.tf line 63, in output "db_instance_name":
│   63:   value       = try(aws_db_instance.this[0].name, "")
```

fix: Replace deprecated name property in outputs

---

examples/cross-region-replica-postgres/README.md
examples/cross-region-replica-postgres/main.tf

If you create an encrypted read replica in a different AWS Region, then you must specify a KMS key identifier for the destination AWS Region. 
Fixes error: 
```
Error: Error creating DB Instance: InvalidParameterCombination: Cannot create a cross region unencrypted read replica from encrypted source.
```
No

fix: Fixed example of cross-region replica where KMS key was missing

---

README.md
variables.tf

I added information about the usage of password and create_random_password because it is quite confusing at the moment. It should solve the issue #402 .
Fixes #402
Multiple people noticed that it was unclear that setting a value to `password` will not use it if the `create_random_password` was not also set to false at the same time.
No breaking changes.

chore: Added detailed information about usage password and create_random_password

---

README.md
main.tf
modules/db_instance/README.md
modules/db_instance/main.tf
modules/db_instance/variables.tf
variables.tf
versions.tf

Add support for the `network_type` argument.
I've got RDS clusters in production that need to be deployed in dual-stack mode, and this module didn't support that configuration yet.  Instead of maintaining a private fork, I will submit a patch.
The required AWS provider is bumped from 4.6 to 4.28.  This version is where the network_type argument became available.

feat: Add support for `network_type`

---

README.md
variables.tf

- Change default value for `iops` from `0` to `null`
- Already done here in submodule: https://github.com/terraform-aws-modules/terraform-aws-rds/pull/456
This reminder from @lucasvuotto: https://github.com/terraform-aws-modules/terraform-aws-rds/pull/456#issuecomment-1357881179
No breaking changes, replicating already merged change in the submodule
No tests done

fix: Default value of iops in main module

---

modules/db_instance/main.tf

- Revert `ignore_changes` for instance `latest_restorable_time`
- Resolves #478 
- No

fix: Revert `ignore_changes` for instance `latest_restorable_time`

---

modules/db_instance/README.md
modules/db_instance/main.tf
modules/db_instance/variables.tf

Adds `monitoring_role_permissions_boundary` as an input to the enhanced monitoring role
The "enhanced monitoring iam_role" at https://github.com/terraform-aws-modules/terraform-aws-rds/blob/master/modules/db_instance/main.tf#L177-L191 doesn't accept permissions_boundary as an input causing errors in case you want to use the iam_role created by the module and your deployment role requires permissions boundary to be attached to newly created roles.
No.

feat: Add support for permissions boundary on enhanced monitoring role

---

README.md
examples/complete-oracle/main.tf
main.tf
modules/db_instance/README.md
modules/db_instance/main.tf
modules/db_instance/variables.tf
variables.tf

Add support for Oracle nchar_character_set_name
We need to change this value to UTF8.
none

feat: Add support for Oracle `nchar_character_set_name`

---

.pre-commit-config.yaml
README.md
modules/db_instance/README.md
modules/db_instance/outputs.tf
outputs.tf

Adds an output variable mapping for the `listener_endpoint` output of the `aws_db_instance` resource
Please see this link for official docs:
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_instance
This output variable is needed when working with **RDS for SQL Server** and **Always On Availability Group (AG)**
None.
Tested with `terraform apply` since it's just an extra output variable.

feat: Add output for SQL Server `listener_endpoint`

---

examples/complete-mssql/README.md
examples/complete-mssql/main.tf
examples/complete-mysql/README.md
examples/complete-mysql/main.tf
examples/complete-oracle/README.md
examples/complete-oracle/main.tf
examples/complete-postgres/README.md
examples/complete-postgres/main.tf
examples/cross-region-replica-postgres/README.md
examples/cross-region-replica-postgres/main.tf
examples/enhanced-monitoring/README.md
examples/enhanced-monitoring/main.tf
examples/replica-mysql/README.md
examples/replica-mysql/main.tf
examples/replica-postgres/README.md
examples/replica-postgres/main.tf
examples/s3-import-mysql/README.md
examples/s3-import-mysql/main.tf

update examples because they were failing because error:
```
│ Error: Unsupported argument
│ 
│   on .terraform/modules/vpc/main.tf line 1246, in resource "aws_default_vpc" "this":
│ 1246:   enable_classiclink   = null # https://github.com/hashicorp/terraform/issues/31730
│ 
```
Because examples are not working on latest provider
no
- [] I have tested and validated these changes using one or more of the provided `examples/*` projects

chore: Update examples

---

README.md
examples/complete-mysql/main.tf
modules/db_instance/README.md
modules/db_instance/variables.tf
variables.tf

The `allocated_storage` type of the DB Instance is an `integer`, as indicated in the [AWS documentation](https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_Types.html). This change has been reflected in this module, transitioning it from a `string` to a `number`.
To adhere to the AWS API data type convention.
No
The examples already shows data in `number` format, however I test it via different types including both string and number values.

fix: Change `allocated_storage` type from string to number

---

modules/db_instance/main.tf

A regression was introduced via c66cd738 where allocated_storage can only be set on primary instances. However, this should not be a limitation because RDS does allow managing replica storage independently from the primary.

fix: Allow managing `allocated_storage` for replicas

---

.pre-commit-config.yaml
main.tf
modules/db_instance/README.md
modules/db_instance/main.tf
modules/db_instance/variables.tf

This PR splits the two on input so that the `var.db_instance_tags` are only applied to the rds_db_instance, preserving the functionality that if `var.tags` is defined, it will be merged with `var.db_instance_tags`
This change is required because it incorrectly maps `var.db_instance_tags` to all resources associated with the module. This functionality is reserved for the `var.tags` input. `var.db_instance_profile` described as "Additional tags for the DB instance", only these tags should be associated with the `rds_db_instance`
None - backwards compatible since `var.db_instance_tags` and `var.tags` are still merged on `this.db_instance` when present.
I need to test these changes, we have an existing project that this might be applicable in.

fix: Separate `db_instance_tags` from merged `tags` sub-module input

---

.pre-commit-config.yaml
README.md
versions.tf

Revert changes for the required provider definition raised in issue #545 
No breaking changes.

fix: Restore aws to required providers

---

examples/cross-region-replica-postgres/main.tf

Fixed cross-region-replica-postgress example code by disabling create parameter group for database.
`create_db_parameter_group` is set to `true` by default. For postgresql replica it can't be created because parameter group is inherited from source db. This variable must be explicite set to false

docs: Adjust cross-region-replica-postgres example code

---

.github/workflows/pr-title.yml
.github/workflows/pre-commit.yml
.pre-commit-config.yaml
README.md
examples/blue-green-deployment/README.md
examples/complete-mssql/README.md
examples/complete-mysql/README.md
examples/complete-oracle/README.md
examples/complete-postgres/README.md
examples/cross-region-replica-postgres/README.md
examples/enhanced-monitoring/README.md
examples/groups/README.md
examples/replica-mysql/README.md
examples/replica-postgres/README.md
examples/role-association-postgres/README.md
examples/s3-import-mysql/README.md
modules/db_instance/README.md
modules/db_instance_role_association/README.md
modules/db_option_group/README.md
modules/db_parameter_group/README.md
modules/db_subnet_group/README.md

- Update CI workflow versions to latest
- Updates our workflows to use the latest versions
- Removes warnings for Python 3.12 in runners
- No

fix: Update CI workflow versions to latest

---

modules/db_instance/main.tf

This change modifies the `random_id.snapshot_identifier` resource to include `var.snapshot_identifier` in the `keepers` block. This ensures that when the `snapshot_identifier` input changes, a new `final_snapshot_identifier` is generated accordingly.
Previously, changes to the `snapshot_identifier` input did not trigger regeneration of the final snapshot identifier. This could lead to the [DBSnapshotAlreadyExists](https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_CreateDBSnapshot.html) error during the deletion of a DB instance. Including `snapshot_identifier` in the [`keepers`](https://registry.terraform.io/providers/hashicorp/random/latest/docs#resource-keepers) ensures the final snapshot is uniquely tied to the correct input, improving consistency and reliability.
No, this …

feat: Change `final_snapshot_identifier` when `snapshot_identifier` changes
